services:
  web:
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:8080', (res) => { if(res.statusCode !== 200) throw new Error('Not healthy') })",
        ]

      interval: 30s
      timeout: 10s
      retries: 3
